apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ui-frontend-for-deployment-system
  name: ui-frontend-for-deployment-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ui-frontend-for-deployment-system
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: ui-frontend-for-deployment-system
    spec:
      hostname: ui-frontend-for-deployment-system
      containers:
        - name: ui-frontend-for-deployment-system
          image: latonaio/ui-frontend-for-deployment-system:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ui-frontend-for-deployment-system
  name: ui-frontend-for-deployment-system
spec:
  selector:
    run: ui-frontend-for-deployment-system
  type: NodePort
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
      nodePort: 30040
---
